version: '3.8'
services:
  session-store:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    command: redis-server --requirepass password
    volumes:
      - sessions:/data

volumes:
  sessions:
